# Generated by Django 4.0.1 on 2022-01-16 13:13
#디비와 장고를 연결시켜주는 연결고리! -> 이걸 연동시켜주는 명령어를 또 입력해야 함 $ python manage.py migrate


from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HelloWorld',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
            ],
        ),
    ]
